[package]
name = "verify_file"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
infer = "0.19.0"
sha2 = "0.10.9"
log = "0.4.21"
env_logger = "0.11.3"
clap = { version = "4.5.4", features = ["derive"] }
